// <auto-generated />
using System;
using Experimento.Data.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Experimento.Data.Migrations
{
    [DbContext(typeof(ExperimentoContext))]
    [Migration("20240823201330_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Experimento.Domain.Entities.Ride", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar")
                        .HasColumnName("Id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime")
                        .HasColumnName("Date");

                    b.Property<string>("RiderId")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.HasKey("Id")
                        .HasName("PK_RIDE");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("RiderId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Ride", (string)null);
                });

            modelBuilder.Entity("Experimento.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar")
                        .HasColumnName("Id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("Name");

                    b.HasKey("Id")
                        .HasName("PK_USER");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Experimento.Domain.Entities.Vehicle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar")
                        .HasColumnName("Id");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("Capacity");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("Plate");

                    b.HasKey("Id")
                        .HasName("PK_VEHICLE");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("OwnerId");

                    b.ToTable("Vehicle", (string)null);
                });

            modelBuilder.Entity("Experimento.Domain.Entities.Ride", b =>
                {
                    b.HasOne("Experimento.Domain.Entities.User", "Rider")
                        .WithMany()
                        .HasForeignKey("RiderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Experimento.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rider");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Experimento.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("Experimento.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });
#pragma warning restore 612, 618
        }
    }
}
