version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carona
      MYSQL_USER: siuari
      MYSQL_PASSWORD: 12345
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306