version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgress_copilot_psql
    environment:
      POSTGRES_DB: copilot
      POSTGRES_USER: copilot
      POSTGRES_PASSWORD: copilot123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
